"""Authentication — users table, password hashing, JWT, FastAPI dependency."""
import re
import uuid
import shutil
import sqlite3
import logging
import hashlib
from datetime import datetime, timezone, timedelta

import bcrypt
from fastapi import Depends, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt, JWTError

from backend.config import settings
from backend.storage.database import get_db

logger = logging.getLogger("uvicorn")

bearer_scheme = HTTPBearer()

JWT_ALGORITHM = "HS256"
JWT_EXPIRE_DAYS = 7

# Valid user_id pattern: 8 hex characters (generated by uuid4().hex[:8] or sha256[:8])
_USER_ID_PATTERN = re.compile(r"^[a-f0-9]{8}$")


def _hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def _verify_password(password: str, hashed: str) -> bool:
    return bcrypt.checkpw(password.encode("utf-8"), hashed.encode("utf-8"))


def _init_user_knowledge(user_id: str):
    """Copy global knowledge base and topics.json to a new user's data directory."""
    global_knowledge = settings.base_dir / "data" / "knowledge"
    global_topics = settings.base_dir / "data" / "topics.json"

    user_knowledge = settings.user_knowledge_path(user_id)
    user_topics = settings.user_topics_path(user_id)

    # Copy knowledge files if global source exists and user doesn't have them yet
    if global_knowledge.exists() and not user_knowledge.exists():
        shutil.copytree(global_knowledge, user_knowledge)
        logger.info(f"Initialized knowledge for user {user_id}")

    # Copy topics.json
    if global_topics.exists() and not user_topics.exists():
        user_topics.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(global_topics, user_topics)
        logger.info(f"Initialized topics.json for user {user_id}")


def _default_user_id(email: str) -> str:
    """Generate a stable user id for the configured default admin account."""
    normalized = email.lower().strip().encode("utf-8")
    return hashlib.sha256(normalized).hexdigest()[:8]



def ensure_default_user():
    """Create default user from .env config if not exists."""
    email = settings.default_email.lower().strip()
    uid = _default_user_id(email)
    conn = get_db()
    existing = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
    if existing:
        if existing["id"] != uid:
            conn.execute("UPDATE users SET id = ? WHERE email = ?", (uid, email))
            conn.commit()
            logger.warning(
                "Default user id migrated from %s to stable id %s for %s",
                existing["id"],
                uid,
                email,
            )
        _init_user_knowledge(uid)
        return
    hashed = _hash_password(settings.default_password)
    conn.execute(
        "INSERT INTO users (id, email, password, name) VALUES (?, ?, ?, ?)",
        (uid, email, hashed, settings.default_name),
    )
    conn.commit()
    logger.info(f"Default user created: {email} ({uid})")
    _init_user_knowledge(uid)


def create_user(email: str, password: str, name: str = "") -> dict:
    if not settings.allow_registration:
        raise HTTPException(403, "Registration is disabled")
    uid = uuid.uuid4().hex[:8]
    hashed = _hash_password(password)
    conn = get_db()
    try:
        conn.execute(
            "INSERT INTO users (id, email, password, name) VALUES (?, ?, ?, ?)",
            (uid, email.lower().strip(), hashed, name),
        )
        conn.commit()
    except sqlite3.IntegrityError:
        raise HTTPException(409, "Email already registered")
    _init_user_knowledge(uid)
    return {"id": uid, "email": email.lower().strip(), "name": name}


def authenticate_user(email: str, password: str) -> dict | None:
    conn = get_db()
    row = conn.execute(
        "SELECT * FROM users WHERE email = ?", (email.lower().strip(),)
    ).fetchone()
    if not row or not _verify_password(password, row["password"]):
        return None
    _init_user_knowledge(row["id"])
    return {"id": row["id"], "email": row["email"], "name": row["name"]}


def create_token(user_id: str) -> str:
    expire = datetime.now(timezone.utc) + timedelta(days=JWT_EXPIRE_DAYS)
    return jwt.encode(
        {"sub": user_id, "exp": expire},
        settings.jwt_secret,
        algorithm=JWT_ALGORITHM,
    )


def get_current_user(
    cred: HTTPAuthorizationCredentials = Depends(bearer_scheme),
) -> str:
    """FastAPI dependency — returns user_id string.

    Validates that user_id matches expected format to prevent path traversal.
    """
    try:
        payload = jwt.decode(
            cred.credentials, settings.jwt_secret, algorithms=[JWT_ALGORITHM]
        )
        user_id = payload.get("sub")
        if not user_id:
            raise HTTPException(401, "Invalid token")
        # Validate user_id format to prevent path traversal attacks
        if not _USER_ID_PATTERN.match(user_id):
            logger.warning(f"Rejected token with invalid user_id format: {user_id!r}")
            raise HTTPException(401, "Invalid token")
        return user_id
    except JWTError:
        raise HTTPException(401, "Invalid or expired token")


def require_owner(user_id: str = Depends(get_current_user)) -> str:
    """Restrict an endpoint to the configured default/owner account.

    The AI channel pool is global (not per-user); without this, any registered
    user could rewrite everyone's LLM/embedding/ASR config or point traffic at an
    attacker-controlled endpoint. Reduces to a no-op in single-user deployments.
    """
    if user_id != _default_user_id(settings.default_email):
        raise HTTPException(403, "Owner only")
    return user_id


def get_user_by_id(user_id: str) -> dict | None:
    conn = get_db()
    row = conn.execute("SELECT id, email, name, created_at FROM users WHERE id = ?", (user_id,)).fetchone()
    if not row:
        return None
    return {"id": row["id"], "email": row["email"], "name": row["name"], "created_at": row["created_at"]}


def update_user_profile(user_id: str, name: str = None, email: str = None) -> dict:
    conn = get_db()
    if name is not None:
        conn.execute("UPDATE users SET name = ? WHERE id = ?", (name.strip(), user_id))
    if email is not None:
        email = email.lower().strip()
        existing = conn.execute("SELECT id FROM users WHERE email = ? AND id != ?", (email, user_id)).fetchone()
        if existing:
            raise HTTPException(409, "Email already in use")
        conn.execute("UPDATE users SET email = ? WHERE id = ?", (email, user_id))
    conn.commit()
    return get_user_by_id(user_id)


def change_user_password(user_id: str, current_password: str, new_password: str) -> bool:
    conn = get_db()
    row = conn.execute("SELECT password FROM users WHERE id = ?", (user_id,)).fetchone()
    if not row or not _verify_password(current_password, row["password"]):
        return False
    hashed = _hash_password(new_password)
    conn.execute("UPDATE users SET password = ? WHERE id = ?", (hashed, user_id))
    conn.commit()
    return True
